name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  sanity-check:
    uses: yoerinijs/vienna/.github/workflows/sanity_checks.yml@main

  build:
    runs-on: ubuntu-latest
    needs: sanity-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: setup
        run: |
          npm install
          npm version patch --no-git-tag-version
          npm run build

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          NEW_FRAMEWORK_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | tr -d '[[:space:]]')
          git add package.json CHANGELOG.md
          git commit -m "feat(package.json): release '$NEW_FRAMEWORK_VERSION'" --no-verify
          git push origin master --no-verify
          git tag -a "$NEW_FRAMEWORK_VERSION" -m "Release $NEW_FRAMEWORK_VERSION"
          git push --tags --no-verify

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}